### ISSUE TITLE
encoidng error

### ISSUE THREAD

**Issue by tencrance** [vinay20045/json-to-csv#1]
Traceback (most recent call last):
  File "json_to_csv.py", line 92, in <module>
    reduce_item(node, item)
  File "json_to_csv.py", line 68, in reduce_item
    reduce_item(key+'_'+str(sub_key), value[sub_key])
  File "json_to_csv.py", line 72, in reduce_item
    reduced_item[str(key)] = str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 49: ordinal not in range(128)

**Comment by chrism91** [comment]
I have this same error. Any fixes or updates?

**Comment by vinay20045** [comment]
Sorry for the radio silence, I was, somehow, not getting notification mails. Anyways, I am looking into the PR and will merge it asap...

**Comment by manu007sharma** [comment]
Hi Vinay- How can I use it on Python IDE or Pycharm. I have share the detailed problem on your E Mail ID. But yes, Its really helpful, though I was not able to convert the response completely. 
Thanks in advance for all your help!
