### ISSUE TITLE
not working for my json

### ISSUE THREAD

**Issue by saurabhbidwai** [vinay20045/json-to-csv#13]
{
        
        "ASSETS" : { "ASSET" :[{
                
        "BND_CORP" : {
                
        "ACCRUAL_DT" : "12/22/2016",
        "AMT_ISU" : "400000000",
        "ANNOUNCE_DT" : "12/8/2016",
        "CALC_TYPE" : "1",
        "CALL_TYPE" : "A",
        "CD_INSTMT_TYPE" : "UNKNOWN",
        "CHANGE_DT" : "2/1/2017 16:07:29.203",
        "COMPOUND_FLAG" : "0",
        "COUNTRY" : "US",
        "COUPON_FIX" : "5.25",
        "COUP_FREQ" : "S",
        "CPN_TYPE" : "F",
        "CURRENCY" : "USD",
        "CUSIP" : "00081TAJ7",
        "CUSIP2_set" : { "CUSIP2_record" :[{
                
        "CODE" : "A",
        "IDENTIFIER" : "00081TAJ7"
    },{
                
        "CODE" : "B",
        "IDENTIFIER" : "AL6700754"
    },{
                
        "CODE" : "C",
        "IDENTIFIER" : "BZ78G47"
    },{
                
        "CODE" : "I",
        "IDENTIFIER" : "US00081TAJ79"
    },{
                
        "CODE" : "R",
        "IDENTIFIER" : "0x00102c5485480bae"
    }] },
        "CUSIP_ALIAS_set" : { "CUSIP_ALIAS_record" :[{
                
        "CODE" : "8001",
        "IDENTIFIER" : "825328116",
        "PURPOSE" : "DEBTID"
    },{
                
        "CODE" : "145986",
        "IDENTIFIER" : "F_12176095",
        "PURPOSE" : "PPMG"
    },{
                
        "CODE" : "145986",
        "IDENTIFIER" : "F_12182768",
        "PURPOSE" : "PPMG"
    }] },
        "CUSIP_TYPE" : "CUSIP",
        "DATE_CONV" : "D30360",
        "DESC_INSTMT" : "ACCO BRANDS CORP",
        "END_ADJ_FLAG" : "N",
        "FIRST_PAY_DT" : "6/15/2017",
        "FIRST_SETTLE_DT" : "12/22/2016",
        "FLAG_144A" : "Y",
        "FLAG_CCN" : "N",
        "FLAG_CONVERT" : "N",
        "FLAG_EOM" : "N",
        "FLAG_ERISA" : "N",
        "FLAG_PERFORMING" : "Y",
        "FLAG_REG_RIGHTS" : "N",
        "ISSUER_ID" : "C08578",
        "ISSUE_DT" : "12/22/2016",
        "ISSUE_EXCHANGES_set" : {
                "SIZE" : "1",
    
        "ISSUE_EXCHANGES_record" : {
                
        "EXCHANGE" : "NSD"
    }
    },
        "ISSUE_PRICE" : "100",
        "ISSUE_YIELD" : "5.25",
        "LEH_INDUSTRY" : "CONS",
        "LIQUIDITY" : "L",
        "MAKE_WHOLE_CALL" : "Y",
        "MAKE_WHOLE_SPREAD" : "0.5",
        "MARKET" : "US",
        "MARKET_ISSUE" : "PUBLIC",
        "MATURITY" : "12/15/2024",
        "MAX_CALL_NOTICE" : "60",
        "MIN_CALL_NOTICE" : "30",
        "MIN_LOT_SIZE" : "1000",
        "MIN_TRD_SIZE" : "2000",
        "MODIFIED_BY" : "sm_timestamp",
        "MTN" : "N",
        "NOTES_set" : { "NOTES_record" :[{
                
        "EFF_DT" : "12/9/2016",
        "INSTMT" : "144A_RegRights exempt",
        "SEQ_NUM" : "1",
        "USER_ID" : "mgalati"
    },{
                
        "EFF_DT" : "12/22/2016",
        "INSTMT" : "Reuters defined: Not yet Issued",
        "SEQ_NUM" : "0",
        "USER_ID" : "EjvDescr"
    },{
                
        "EFF_DT" : "2/1/2017",
        "INSTMT" : "risk country per PPMG",
        "SEQ_NUM" : "10",
        "USER_ID" : "ntodorov"
    },{
                
        "EFF_DT" : "2/21/2017",
        "INSTMT" : "144A_RegRights exempt",
        "SEQ_NUM" : "500",
        "USER_ID" : "cmay"
    }] },
        "NTL_FLAG" : "N",
        "PC_DAY_CONV" : "C",
        "PMT_ADJ_METH" : "F",
        "PMT_CAL" : "NY_Bank",
        "PMT_FREQ_TYPE" : "0",
        "PMT_LOCATION" : "D",
        "PRICE_AS_PCT" : "Y",
        "PUTCALL_set" : { "PUTCALL_record" :[{
                
        "DT" : "12/15/2019",
        "PRICE" : "103.938",
        "TYPE" : "C"
    },{
                
        "DT" : "12/15/2020",
        "PRICE" : "102.625",
        "TYPE" : "C"
    },{
                
        "DT" : "12/15/2021",
        "PRICE" : "101.313",
        "TYPE" : "C"
    },{
                
        "DT" : "12/15/2022",
        "PRICE" : "100",
        "TYPE" : "C"
    }] },
        "PUT_CALL" : "C",
        "RATING_set" : { "RATING_record" :[{
                
        "AGY" : "1",
        "DATE" : "12/8/2016",
        "VALUE" : "B1"
    },{
                
        "AGY" : "2",
        "DATE" : "12/8/2016",
        "VALUE" : "BB-"
    },{
                
        "AGY" : "3",
        "DATE" : "12/8/2016",
        "VALUE" : "BB"
    },{
                
        "AGY" : "14",
        "DATE" : "3/20/2017",
        "VALUE" : "BB-"
    },{
                
        "AGY" : "45",
        "DATE" : "12/8/2016",
        "VALUE" : "3(55)"
    }] },
        "REVIEWED_BY" : "jedinger",
        "RISK_COUNTRY" : "US",
        "ROUND_FLAG" : "R",
        "ROUND_PRECISION" : "9",
        "SAL_INDUSTRY" : "CONS",
        "SECTOR_set" : { "SECTOR_record" :[{
                
        "CODE" : "CONS",
        "LEVEL" : "1",
        "SECTOR_SOURCE" : "P",
        "TYPE" : "BARC_SECT"
    },{
                
        "CODE" : "CONP",
        "LEVEL" : "1",
        "TYPE" : "ISS_ML"
    }] },
        "SEC_TYPE" : "BND_CORP",
        "SETTLE_LOCATION" : "D",
        "SM_SEC_GROUP" : "BND",
        "SM_SEC_TYPE" : "CORP",
        "STRUCTURE" : "SENIOR",
        "TICKER" : "ACCO",
        "UDF_set" : { "UDF_record" :[{
                
        "LABEL" : "EXP_DFLT_MARGIN",
        "PURPOSE" : "PPMG",
        "UDF_SOURCE" : "PPMG",
        "VALUE" : "139.28000000000000"
    },{
                
        "LABEL" : "FINANCIAL_SEC",
        "PURPOSE" : "MNG",
        "UDF_SOURCE" : "MNG",
        "VALUE" : "Non-Financial"
    },{
                
        "LABEL" : "PPMG_SEDOL",
        "PURPOSE" : "PPMG",
        "UDF_SOURCE" : "PPMG",
        "VALUE" : "9885662"
    }] },
        "UNITS" : "BONDS",
        "WI_FLAG" : "N"
    }
    },{
                
        "BND_CORP" : {
                
        "ACCRUAL_DT" : "6/4/2015",
        "AMT_ISU" : "1000000000",
        "ANNOUNCE_DT" : "5/28/2015",
        "CALC_TYPE" : "1",
        "CALL_MANDATORY" : "N",
        "CD_INSTMT_TYPE" : "UNKNOWN",
        "CHANGE_DT" : "2/1/2017 16:07:15.670",
        "COMPOUND_FLAG" : "0",
        "COUNTRY" : "NL",
        "COUPON_FIX" : "2.45",
        "COUP_FREQ" : "S",
        "CPN_TYPE" : "F",
        "CURRENCY" : "USD",
        "CUSIP" : "00084DAJ9",
        "CUSIP2_set" : { "CUSIP2_record" :[{
                
        "CODE" : "B",
        "IDENTIFIER" : "EK9442097"
    },{
                
        "CODE" : "C",
        "IDENTIFIER" : "BYR8K93"
    },{
                
        "CODE" : "I",
        "IDENTIFIER" : "US00084DAJ90"
    }] },
        "CUSIP_ALIAS_set" : { "CUSIP_ALIAS_record" :[{
                
        "CODE" : "8001",
        "IDENTIFIER" : "824536165",
        "PURPOSE" : "DEBTID"
    },{
                
        "CODE" : "145986",
        "IDENTIFIER" : "F_10345013",
        "PURPOSE" : "PPMG"
    }] },
        "CUSIP_TYPE" : "CUSIP",
        "DATE_CONV" : "D30360",
        "DESC_INSTMT" : "ABN AMRO BANK NV",
        "END_ADJ_FLAG" : "N",
        "FIRST_PAY_DT" : "12/4/2015",
        "FIRST_SETTLE_DT" : "6/4/2015",
        "FLAG_144A" : "Y",
        "FLAG_EOM" : "N",
        "FLAG_ERISA" : "N",
        "FLAG_PERFORMING" : "Y",
        "FLAG_REG_RIGHTS" : "N",
        "ISSUER_ID" : "E97445",
        "ISSUE_DT" : "6/4/2015",
        "ISSUE_EXCHANGES_set" : { "ISSUE_EXCHANGES_record" :[{
                
        "EXCHANGE" : "AEX"
    },{
                
        "EXCHANGE" : "NSD"
    }] },
        "ISSUE_PRICE" : "99.78",
        "LEH_INDUSTRY" : "BANK",
        "LIQUIDITY" : "L",
        "MARKET" : "US",
        "MATURITY" : "6/4/2020",
        "MIN_LOT_SIZE" : "1000",
        "MIN_TRD_SIZE" : "200000",
        "MODIFIED_BY" : "sm_timestamp",
        "MTN" : "Y",
        "NOTES_set" : { "NOTES_record" :[{
                
        "EFF_DT" : "6/1/2015",
        "INSTMT" : "144A_RegRights exempt",
        "SEQ_NUM" : "2",
        "USER_ID" : "alogan"
    },{
                
        "EFF_DT" : "1/1/2016",
        "INSTMT" : "144A_RegRights exempt",
        "SEQ_NUM" : "2",
        "USER_ID" : "alogan"
    },{
                
        "EFF_DT" : "2/1/2017",
        "INSTMT" : "risk country per PPMG",
        "SEQ_NUM" : "10",
        "USER_ID" : "ntodorov"
    }] },
        "NTL_FLAG" : "N",
        "PC_DAY_CONV" : "B",
        "PMT_ADJ_METH" : "F",
        "PMT_CAL" : "NY_Bank",
        "PMT_FREQ_TYPE" : "0",
        "PMT_LOCATION" : "D",
        "PRICE_AS_PCT" : "Y",
        "PUT_CALL" : " ",
        "PUT_MANDATORY" : "N",
        "RATING_set" : { "RATING_record" :[{
                
        "AGY" : "1",
        "DATE" : "5/20/2016",
        "VALUE" : "A1"
    },{
                
        "AGY" : "2",
        "DATE" : "5/29/2015",
        "VALUE" : "A"
    },{
                
        "AGY" : "3",
        "DATE" : "2/24/2017",
        "VALUE" : "A+"
    },{
                
        "AGY" : "14",
        "DATE" : "3/20/2017",
        "VALUE" : "A-"
    }] },
        "REVIEWED_BY" : "mtang",
        "RISK_COUNTRY" : "NL",
..................................................................................................

tried with ASSETS, ASSET and BND_CORP nodes but still getting output with only 1 column

**Comment by vinay20045** [comment]
There is a depth issue with your JSON. The `node` element has to be at the first level for the script to work. Try this...

Modify your original JSON that looks like this...
```
{
    "ASSETS" : {
        "ASSET" :[
            {
                "BND_CORP" : {            
                    "ACCRUAL_DT" : "12/22/2016",
                    "AMT_ISU" : "400000000",
                    ......
                }
            }
        ]
    }
}
```
to look like this...
```
{
    "ASSET" :[
        {
            "BND_CORP" : {            
                "ACCRUAL_DT" : "12/22/2016",
                "AMT_ISU" : "400000000",
                ......
            }
        }
    ]
}
```

and then run the script with ASSET as the node element. I got a CSV of 148 cols with this structure.

Let me know...
