### ISSUE TITLE
but what about this json which has no node?? 

### ISSUE THREAD

**Issue by saurabhbidwai** [vinay20045/json-to-csv#14]
{"created_at":"Sun Jul 02 03:09:52 +0000 2017","id":881349174587002880,"id_str":"881349174587002880","text":"RT @Lutho__m: If you using mtn join AfriHost #MTNisTrash \nRT to help fellow tweeps\n\n500MB - R29\n1Gig - R58\n2Gig - R99\n3Gig - R145\n4Gig - R1\u2026","source":"\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":2806021774,"id_str":"2806021774","name":"van wyk money","screen_name":"agneshleli","location":"in my zone","url":null,"description":"doing the damn thing.","protected":false,"verified":false,"followers_count":343,"friends_count":167,"listed_count":3,"favourites_count":315,"statuses_count":8483,"created_at":"Sat Oct 04 18:29:06 +0000 2014","utc_offset":null,"time_zone":null,"geo_enabled":true,"lang":"en","contributors_enabled":false,"is_translator":false,"profile_background_color":"C0DEED","profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_tile":false,"profile_link_color":"1DA1F2","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/841333464087572481\/6o6xWxL0_normal.jpg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/841333464087572481\/6o6xWxL0_normal.jpg","profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/2806021774\/1441472196","default_profile":true,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"retweeted_status":{"created_at":"Sat Jul 01 09:44:15 +0000 2017","id":881086035022761984,"id_str":"881086035022761984","text":"If you using mtn join AfriHost #MTNisTrash \nRT to help fellow tweeps\n\n500MB - R29\n1Gig - R58\n2Gig - R99\n3Gig - R145\n4Gig - R197\n5Gig - R247","source":"\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":835234814924029952,"id_str":"835234814924029952","name":"\ud83d\udc51 XHOSA PRINCE\ud83c\udf6b","screen_name":"Lutho__m","location":"Cape Town \/\/ Engcobo","url":"http:\/\/atripwithlutho.wordpress.com","description":"Xhosa Choco \ud83c\udf6b| #TTZA i rep \ud83d\udc80 \ud83d\udcc8 | My tweets are mostly my thoughts \ud83d\ude0e | Check Likes \ud83d\udd25| my life's story is in my blog go check it out if you interested \u263a\ud83d\ude0a","protected":false,"verified":false,"followers_count":18608,"friends_count":16875,"listed_count":16,"favourites_count":1374,"statuses_count":8828,"created_at":"Fri Feb 24 21:07:52 +0000 2017","utc_offset":null,"time_zone":null,"geo_enabled":true,"lang":"en","contributors_enabled":false,"is_translator":false,"profile_background_color":"F5F8FA","profile_background_image_url":"","profile_background_image_url_https":"","profile_background_tile":false,"profile_link_color":"1DA1F2","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/865206311922749440\/ol8Aj4As_normal.jpg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/865206311922749440\/ol8Aj4As_normal.jpg","profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/835234814924029952\/1496065852","default_profile":true,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":1209,"favorite_count":633,"entities":{"hashtags":[{"text":"MTNisTrash","indices":[31,42]}],"urls":[],"user_mentions":[],"symbols":[]},"favorited":false,"retweeted":false,"filter_level":"low","lang":"en"},"is_quote_status":false,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[{"text":"MTNisTrash","indices":[45,56]}],"urls":[],"user_mentions":[{"screen_name":"Lutho__m","name":"\ud83d\udc51 XHOSA PRINCE\ud83c\udf6b","id":835234814924029952,"id_str":"835234814924029952","indices":[3,12]}],"symbols":[]},"favorited":false,"retweeted":false,"filter_level":"low","lang":"en","timestamp_ms":"1498964992554"}
{"created_at":"Sun Jul 02 03:10:13 +0000 2017","id":881349262835101696,"id_str":"881349262835101696","text":"RT @flxriantheonly: avant qd j'\u00e9tais petit le moment d'aller me coucher j'le d\u00e9testais j'comprend pas pq pcq mtn c'est devenu mon moment pr\u2026","source":"\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":3732973155,"id_str":"3732973155","name":"` Ju `","screen_name":"justine_dwd","location":"JUL ","url":null,"description":"DYLAN.\u2661","protected":false,"verified":false,"followers_count":232,"friends_count":95,"listed_count":3,"favourites_count":1322,"statuses_count":14335,"created_at":"Mon Sep 21 23:28:52 +0000 2015","utc_offset":null,"time_zone":null,"geo_enabled":false,"lang":"fr","contributors_enabled":false,"is_translator":false,"profile_background_color":"C0DEED","profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_tile":false,"profile_link_color":"1DA1F2","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/881234496519065600\/0WefTQuj_normal.jpg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/881234496519065600\/0WefTQuj_normal.jpg","profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/3732973155\/1444091879","default_profile":true,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"retweeted_status":{"created_at":"Mon Jun 19 17:11:43 +0000 2017","id":876849989691076608,"id_str":"876849989691076608","text":"avant qd j'\u00e9tais petit le moment d'aller me coucher j'le d\u00e9testais j'comprend pas pq pcq mtn c'est devenu mon moment pr\u00e9f\u00e9r\u00e9 de la journ\u00e9e","source":"\u003ca href=\"http:\/\/twitter.com\" rel=\"nofollow\"\u003eTwitter Web Client\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":2316935620,"id_str":"2316935620","name":"snap : florianlmh86","screen_name":"flxriantheonly","location":"Niort,Poitiers ","url":null,"description":"Sinon \u00e7a fais moche sans bio mdr","protected":false,"verified":false,"followers_count":21536,"friends_count":7605,"listed_count":87,"favourites_count":13096,"statuses_count":1063,"created_at":"Fri Jan 31 21:43:29 +0000 2014","utc_offset":7200,"time_zone":"Paris","geo_enabled":false,"lang":"fr","contributors_enabled":false,"is_translator":false,"profile_background_color":"FF6699","profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme11\/bg.gif","profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme11\/bg.gif","profile_background_tile":true,"profile_link_color":"FAB81E","profile_sidebar_border_color":"FFFFFF","profile_sidebar_fill_color":"E5507E","profile_text_color":"362720","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/876236500589060096\/Ra0dSeKK_normal.jpg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/876236500589060096\/Ra0dSeKK_normal.jpg","profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/2316935620\/1497745958","default_profile":false,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":1001,"favorite_count":515,"entities":{"hashtags":[],"urls":[],"user_mentions":[],"symbols":[]},"favorited":false,"retweeted":false,"filter_level":"low","lang":"fr"},"is_quote_status":false,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[],"urls":[],"user_mentions":[{"screen_name":"flxriantheonly","name":"snap : florianlmh86","id":2316935620,"id_str":"2316935620","indices":[3,18]}],"symbols":[]},"favorited":false,"retweeted":false,"filter_level":"low","lang":"fr","timestamp_ms":"1498965013594"}
{"created_at":"Sun Jul 02 03:10:48 +0000 2017","id":881349407802888192,"id_str":"881349407802888192","text":"MoMoPay Arrives in Africa via MTN Benin and Youtap https:\/\/t.co\/yCBg5MVrrK #payments https:\/\/t.co\/wUO774x1Aq\u2026 https:\/\/t.co\/V4oFnbuEJv","display_text_range":[0,140],"source":"\u003ca href=\"https:\/\/www.socialoomph.com\" rel=\"nofollow\"\u003eSocialOomph\u003c\/a\u003e","truncated":true,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":50151799,"id_str":"50151799","name":"CardFlash News","screen_name":"CardFlash","location":"Naples, Florida","url":"http:\/\/www.cardflash.com","description":"CARDFLASH\u00ae is THE ORIGINAL News Service Reporting on the Payment Card Industry Daily Since 1986.  Over 200,000 Paid Subscribers !","protected":false,"verified":false,"followers_count":856,"friends_count":1219,"listed_count":172,"favourites_count":2,"statuses_count":7620,"created_at":"Wed Jun 24 00:18:32 +0000 2009","utc_offset":-14400,"time_zone":"Eastern Time (US & Canada)","geo_enabled":true,"lang":"en","contributors_enabled":false,"is_translator":false,"profile_background_color":"A3A3A3","profile_background_image_url":"http:\/\/pbs.twimg.com\/profile_background_images\/558286616\/cardflash_twitter_bg.png","profile_background_image_url_https":"https:\/\/pbs.twimg.com\/profile_background_images\/558286616\/cardflash_twitter_bg.png","profile_background_tile":false,"profile_link_color":"20C200","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/2239046993\/cardflash_squarelogo_normal.png","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/2239046993\/cardflash_squarelogo_normal.png","default_profile":false,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"extended_tweet":{"full_text":"MoMoPay Arrives in Africa via MTN Benin and Youtap https:\/\/t.co\/yCBg5MVrrK #payments https:\/\/t.co\/wUO774x1Aq #CardFlash https:\/\/t.co\/eDN3ZT3iSl","display_text_range":[0,119],"entities":{"hashtags":[{"text":"payments","indices":[75,84]},{"text":"CardFlash","indices":[109,119]}],"urls":[{"url":"https:\/\/t.co\/yCBg5MVrrK","expanded_url":"http:\/\/dld.bz\/fQHTN","display_url":"dld.bz\/fQHTN","indices":[51,74]},{"url":"https:\/\/t.co\/wUO774x1Aq","expanded_url":"http:\/\/www.cardflash.com","display_url":"cardflash.com","indices":[85,108]}],"user_mentions":[],"symbols":[],"media":[{"id":881349403872808960,"id_str":"881349403872808960","indices":[120,143],"media_url":"http:\/\/pbs.twimg.com\/media\/DDsunPzXUAAZBOJ.jpg","media_url_https":"https:\/\/pbs.twimg.com\/media\/DDsunPzXUAAZBOJ.jpg","url":"https:\/\/t.co\/eDN3ZT3iSl","display_url":"pic.twitter.com\/eDN3ZT3iSl","expanded_url":"https:\/\/twitter.com\/CardFlash\/status\/881349407802888192\/photo\/1","type":"photo","sizes":{"thumb":{"w":150,"h":150,"resize":"crop"},"large":{"w":1186,"h":1132,"resize":"fit"},"medium":{"w":1186,"h":1132,"resize":"fit"},"small":{"w":680,"h":649,"resize":"fit"}}}]},"extended_entities":{"media":[{"id":881349403872808960,"id_str":"881349403872808960","indices":[120,143],"media_url":"http:\/\/pbs.twimg.com\/media\/DDsunPzXUAAZBOJ.jpg","media_url_https":"https:\/\/pbs.twimg.com\/media\/DDsunPzXUAAZBOJ.jpg","url":"https:\/\/t.co\/eDN3ZT3iSl","display_url":"pic.twitter.com\/eDN3ZT3iSl","expanded_url":"https:\/\/twitter.com\/CardFlash\/status\/881349407802888192\/photo\/1","type":"photo","sizes":{"thumb":{"w":150,"h":150,"resize":"crop"},"large":{"w":1186,"h":1132,"resize":"fit"},"medium":{"w":1186,"h":1132,"resize":"fit"},"small":{"w":680,"h":649,"resize":"fit"}}}]}},"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[{"text":"payments","indices":[75,84]}],"urls":[{"url":"https:\/\/t.co\/yCBg5MVrrK","expanded_url":"http:\/\/dld.bz\/fQHTN","display_url":"dld.bz\/fQHTN","indices":[51,74]},{"url":"https:\/\/t.co\/wUO774x1Aq","expanded_url":"http:\/\/www.cardflash.com","display_url":"cardflash.com","indices":[85,108]},{"url":"https:\/\/t.co\/V4oFnbuEJv","expanded_url":"https:\/\/twitter.com\/i\/web\/status\/881349407802888192","display_url":"twitter.com\/i\/web\/status\/8\u2026","indices":[110,133]}],"user_mentions":[],"symbols":[]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"filter_level":"low","lang":"en","timestamp_ms":"1498965048157"}
{"created_at":"Sun Jul 02 03:10:51 +0000 2017","id":881349422910779392,"id_str":"881349422910779392","text":"C'est bon je viens te faire chier L\u00e9a, mtn je peux essayer de dormir mdrrr. Elle va gueuler mais c'est pas grave \u00e0 force j'ai l'habitude","source":"\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":4734361875,"id_str":"4734361875","name":"Shanel Dreze\u2665","screen_name":"DrezeShanel","location":null,"url":null,"description":"Marion\/Margot\u2764\ufe0f Ali,L\u00e9a\u2764\ufe0f 15 ans\ud83c\udf82","protected":false,"verified":false,"followers_count":387,"friends_count":504,"listed_count":0,"favourites_count":812,"statuses_count":827,"created_at":"Thu Jan 07 12:23:12 +0000 2016","utc_offset":null,"time_zone":null,"geo_enabled":false,"lang":"fr","contributors_enabled":false,"is_translator":false,"profile_background_color":"F5F8FA","profile_background_image_url":"","profile_background_image_url_https":"","profile_background_tile":false,"profile_link_color":"1DA1F2","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/876577186865700864\/PcS4dpiX_normal.jpg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/876577186865700864\/PcS4dpiX_normal.jpg","profile_banner_url":"https:\/\/pbs.twimg.com\/profile_banners\/4734361875\/1496366327","default_profile":true,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[],"urls":[],"user_mentions":[],"symbols":[]},"favorited":false,"retweeted":false,"filter_level":"low","lang":"fr","timestamp_ms":"1498965051759"}

**Comment by vinay20045** [comment]
Your JSON is malformed. Try https://jsonlint.com/ to check errors in your JSON. 

Ex: The below field has unescaped quotation marks before the URL.
```
"source":"\u003ca href="http://twitter.com/download/android" rel="nofollow"\u003eTwitter for Android\u003c/a\u003e"
```

If your JSON is correct and you're still facing issues in conversion, please reply with error log and more details about your environment.

**Comment by saurabhbidwai** [comment]
new this is the valid json but still it is giving me wrong output with "tweets" node

{
	"tweets": {
		"created_at": "Sun Jul 02 03:09:52 +0000 2017",
		"id": 881349174587002880,
		"id_str": "881349174587002880",
		"text": "RT @Lutho__m: If you using mtn join AfriHost #MTNisTrash \nRT to help fellow tweeps\n\n500MB - R29\n1Gig - R58\n2Gig - R99\n3Gig - R145\n4Gig - R1\u2026",
		"source": "\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e",
		"truncated": false,
		"in_reply_to_status_id": null,
		"in_reply_to_status_id_str": null,
		"in_reply_to_user_id": null,
		"in_reply_to_user_id_str": null,
		"in_reply_to_screen_name": null,
		"user": {
			"id": 2806021774,
			"id_str": "2806021774",
			"name": "van wyk money",
			"screen_name": "agneshleli",
			"location": "in my zone",
			"url": null,
			"description": "doing the damn thing.",
			"protected": false,
			"verified": false,
			"followers_count": 343,
			"friends_count": 167,
			"listed_count": 3,
			"favourites_count": 315,
			"statuses_count": 8483,
			"created_at": "Sat Oct 04 18:29:06 +0000 2014",
			"utc_offset": null,
			"time_zone": null,
			"geo_enabled": true,
			"lang": "en",
			"contributors_enabled": false,
			"is_translator": false,
			"profile_background_color": "C0DEED",
			"profile_background_image_url": "http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
			"profile_background_image_url_https": "https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
			"profile_background_tile": false,
			"profile_link_color": "1DA1F2",
			"profile_sidebar_border_color": "C0DEED",
			"profile_sidebar_fill_color": "DDEEF6",
			"profile_text_color": "333333",
			"profile_use_background_image": true,
			"profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/841333464087572481\/6o6xWxL0_normal.jpg",
			"profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/841333464087572481\/6o6xWxL0_normal.jpg",
			"profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/2806021774\/1441472196",
			"default_profile": true,
			"default_profile_image": false,
			"following": null,
			"follow_request_sent": null,
			"notifications": null
		},
		"geo": null,
		"coordinates": null,
		"place": null,
		"contributors": null,
		"retweeted_status": {
			"created_at": "Sat Jul 01 09:44:15 +0000 2017",
			"id": 881086035022761984,
			"id_str": "881086035022761984",
			"text": "If you using mtn join AfriHost #MTNisTrash \nRT to help fellow tweeps\n\n500MB - R29\n1Gig - R58\n2Gig - R99\n3Gig - R145\n4Gig - R197\n5Gig - R247",
			"source": "\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e",
			"truncated": false,
			"in_reply_to_status_id": null,
			"in_reply_to_status_id_str": null,
			"in_reply_to_user_id": null,
			"in_reply_to_user_id_str": null,
			"in_reply_to_screen_name": null,
			"user": {
				"id": 835234814924029952,
				"id_str": "835234814924029952",
				"name": "\ud83d\udc51 XHOSA PRINCE\ud83c\udf6b",
				"screen_name": "Lutho__m",
				"location": "Cape Town \/\/ Engcobo",
				"url": "http:\/\/atripwithlutho.wordpress.com",
				"description": "Xhosa Choco \ud83c\udf6b| #TTZA i rep \ud83d\udc80 \ud83d\udcc8 | My tweets are mostly my thoughts \ud83d\ude0e | Check Likes \ud83d\udd25| my life's story is in my blog go check it out if you interested \u263a\ud83d\ude0a",
				"protected": false,
				"verified": false,
				"followers_count": 18608,
				"friends_count": 16875,
				"listed_count": 16,
				"favourites_count": 1374,
				"statuses_count": 8828,
				"created_at": "Fri Feb 24 21:07:52 +0000 2017",
				"utc_offset": null,
				"time_zone": null,
				"geo_enabled": true,
				"lang": "en",
				"contributors_enabled": false,
				"is_translator": false,
				"profile_background_color": "F5F8FA",
				"profile_background_image_url": "",
				"profile_background_image_url_https": "",
				"profile_background_tile": false,
				"profile_link_color": "1DA1F2",
				"profile_sidebar_border_color": "C0DEED",
				"profile_sidebar_fill_color": "DDEEF6",
				"profile_text_color": "333333",
				"profile_use_background_image": true,
				"profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/865206311922749440\/ol8Aj4As_normal.jpg",
				"profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/865206311922749440\/ol8Aj4As_normal.jpg",
				"profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/835234814924029952\/1496065852",
				"default_profile": true,
				"default_profile_image": false,
				"following": null,
				"follow_request_sent": null,
				"notifications": null
			},
			"geo": null,
			"coordinates": null,
			"place": null,
			"contributors": null,
			"is_quote_status": false,
			"retweet_count": 1209,
			"favorite_count": 633,
			"entities": {
				"hashtags": [{
					"text": "MTNisTrash",
					"indices": [31, 42]
				}],
				"urls": [],
				"user_mentions": [],
				"symbols": []
			},
			"favorited": false,
			"retweeted": false,
			"filter_level": "low",
			"lang": "en"
		},
		"is_quote_status": false,
		"retweet_count": 0,
		"favorite_count": 0,
		"entities": {
			"hashtags": [{
				"text": "MTNisTrash",
				"indices": [45, 56]
			}],
			"urls": [],
			"user_mentions": [{
				"screen_name": "Lutho__m",
				"name": "\ud83d\udc51 XHOSA PRINCE\ud83c\udf6b",
				"id": 835234814924029952,
				"id_str": "835234814924029952",
				"indices": [3, 12]
			}],
			"symbols": []
		},
		"favorited": false,
		"retweeted": false,
		"filter_level": "low",
		"lang": "en",
		"timestamp_ms": "1498964992554"
	}
}

**Comment by saurabhbidwai** [comment]
This one is also valid json, so what would be the node here?
{
	"created_at": "Sun Jul 02 03:09:52 +0000 2017",
	"id": 881349174587002880,
	"id_str": "881349174587002880",
	"text": "RT @Lutho__m: If you using mtn join AfriHost #MTNisTrash \nRT to help fellow tweeps\n\n500MB - R29\n1Gig - R58\n2Gig - R99\n3Gig - R145\n4Gig - R1\u2026",
	"source": "\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e",
	"truncated": false,
	"in_reply_to_status_id": null,
	"in_reply_to_status_id_str": null,
	"in_reply_to_user_id": null,
	"in_reply_to_user_id_str": null,
	"in_reply_to_screen_name": null,
	"user": {
		"id": 2806021774,
		"id_str": "2806021774",
		"name": "van wyk money",
		"screen_name": "agneshleli",
		"location": "in my zone",
		"url": null,
		"description": "doing the damn thing.",
		"protected": false,
		"verified": false,
		"followers_count": 343,
		"friends_count": 167,
		"listed_count": 3,
		"favourites_count": 315,
		"statuses_count": 8483,
		"created_at": "Sat Oct 04 18:29:06 +0000 2014",
		"utc_offset": null,
		"time_zone": null,
		"geo_enabled": true,
		"lang": "en",
		"contributors_enabled": false,
		"is_translator": false,
		"profile_background_color": "C0DEED",
		"profile_background_image_url": "http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
		"profile_background_image_url_https": "https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
		"profile_background_tile": false,
		"profile_link_color": "1DA1F2",
		"profile_sidebar_border_color": "C0DEED",
		"profile_sidebar_fill_color": "DDEEF6",
		"profile_text_color": "333333",
		"profile_use_background_image": true,
		"profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/841333464087572481\/6o6xWxL0_normal.jpg",
		"profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/841333464087572481\/6o6xWxL0_normal.jpg",
		"profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/2806021774\/1441472196",
		"default_profile": true,
		"default_profile_image": false,
		"following": null,
		"follow_request_sent": null,
		"notifications": null
	},
	"geo": null,
	"coordinates": null,
	"place": null,
	"contributors": null,
	"retweeted_status": {
		"created_at": "Sat Jul 01 09:44:15 +0000 2017",
		"id": 881086035022761984,
		"id_str": "881086035022761984",
		"text": "If you using mtn join AfriHost #MTNisTrash \nRT to help fellow tweeps\n\n500MB - R29\n1Gig - R58\n2Gig - R99\n3Gig - R145\n4Gig - R197\n5Gig - R247",
		"source": "\u003ca href=\"http:\/\/twitter.com\/download\/android\" rel=\"nofollow\"\u003eTwitter for Android\u003c\/a\u003e",
		"truncated": false,
		"in_reply_to_status_id": null,
		"in_reply_to_status_id_str": null,
		"in_reply_to_user_id": null,
		"in_reply_to_user_id_str": null,
		"in_reply_to_screen_name": null,
		"user": {
			"id": 835234814924029952,
			"id_str": "835234814924029952",
			"name": "\ud83d\udc51 XHOSA PRINCE\ud83c\udf6b",
			"screen_name": "Lutho__m",
			"location": "Cape Town \/\/ Engcobo",
			"url": "http:\/\/atripwithlutho.wordpress.com",
			"description": "Xhosa Choco \ud83c\udf6b| #TTZA i rep \ud83d\udc80 \ud83d\udcc8 | My tweets are mostly my thoughts \ud83d\ude0e | Check Likes \ud83d\udd25| my life's story is in my blog go check it out if you interested \u263a\ud83d\ude0a",
			"protected": false,
			"verified": false,
			"followers_count": 18608,
			"friends_count": 16875,
			"listed_count": 16,
			"favourites_count": 1374,
			"statuses_count": 8828,
			"created_at": "Fri Feb 24 21:07:52 +0000 2017",
			"utc_offset": null,
			"time_zone": null,
			"geo_enabled": true,
			"lang": "en",
			"contributors_enabled": false,
			"is_translator": false,
			"profile_background_color": "F5F8FA",
			"profile_background_image_url": "",
			"profile_background_image_url_https": "",
			"profile_background_tile": false,
			"profile_link_color": "1DA1F2",
			"profile_sidebar_border_color": "C0DEED",
			"profile_sidebar_fill_color": "DDEEF6",
			"profile_text_color": "333333",
			"profile_use_background_image": true,
			"profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/865206311922749440\/ol8Aj4As_normal.jpg",
			"profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/865206311922749440\/ol8Aj4As_normal.jpg",
			"profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/835234814924029952\/1496065852",
			"default_profile": true,
			"default_profile_image": false,
			"following": null,
			"follow_request_sent": null,
			"notifications": null
		},
		"geo": null,
		"coordinates": null,
		"place": null,
		"contributors": null,
		"is_quote_status": false,
		"retweet_count": 1209,
		"favorite_count": 633,
		"entities": {
			"hashtags": [{
				"text": "MTNisTrash",
				"indices": [31, 42]
			}],
			"urls": [],
			"user_mentions": [],
			"symbols": []
		},
		"favorited": false,
		"retweeted": false,
		"filter_level": "low",
		"lang": "en"
	},
	"is_quote_status": false,
	"retweet_count": 0,
	"favorite_count": 0,
	"entities": {
		"hashtags": [{
			"text": "MTNisTrash",
			"indices": [45, 56]
		}],
		"urls": [],
		"user_mentions": [{
			"screen_name": "Lutho__m",
			"name": "\ud83d\udc51 XHOSA PRINCE\ud83c\udf6b",
			"id": 835234814924029952,
			"id_str": "835234814924029952",
			"indices": [3, 12]
		}],
		"symbols": []
	},
	"favorited": false,
	"retweeted": false,
	"filter_level": "low",
	"lang": "en",
	"timestamp_ms": "1498964992554"
}

**Comment by vinay20045** [comment]
Firstly, the JSON is still invalid. It still has the same error that I pointed out earlier. Please use https://jsonlint.com/ to check.

But, if I were to do this with valid tweet objects, I would make an array/list of all the tweet objects (like below) and pass it to the script with `tweet` as the node.
```
{
    "tweet": [
        {
            "created_at": "Sun Jul 02 03:09:52 +0000 2017",
            "id": 881349174587002880,
            ...
        },
        {
            "created_at": "Sun Jul 02 03:09:52 +0000 2017",
            "id": 881349174587002880,
            ...
        },
        ...
    ]
}
```

Check out the source specification in the [readme](https://github.com/vinay20045/json-to-csv/blob/master/README.md) file...
