### ISSUE TITLE
Convert multiple json structure in one json file

### ISSUE THREAD

**Issue by cjsgary** [vinay20045/json-to-csv#17]
Hi, can you advice me how to convert the json file if i have more than one json structure inside a  .json 
Example : 

{
  "image_id": "W0pVzdW6XjPFu2fuazKODA==",
  "request_id": "1515662622,c9c626f1-11c7-4584-ba99-b731b7046c44",
  "time_used": 250,
  "faces": [
    {
      "landmark": {
        "contour_chin": {
          "y": 269,
          "x": 73
        },
        "left_eye_upper_left_quarter": {
          "y": 135,
          "x": 67
        },
        "mouth_lower_lip_right_contour1": {
          "y": 230,
          "x": 98
        },
        "left_eye_bottom": {
          "y": 143,
          "x": 72
        },
        "mouth_lower_lip_right_contour2": {
          "y": 238,
          "x": 104
        },
        "contour_left7": {
          "y": 176,
          "x": 49
        },
        "contour_left6": {
          "y": 166,
          "x": 49
        },
        "contour_left5": {
          "y": 157,
          "x": 51
        },
        "contour_left4": {
          "y": 148,
          "x": 54
        },
        "contour_left3": {
          "y": 139,
          "x": 58
        },
        "contour_left2": {
          "y": 131,
          "x": 61
        },
        "contour_left1": {
          "y": 124,
          "x": 64
        },
        "left_eye_lower_left_quarter": {
          "y": 139,
          "x": 66
        },
        "contour_right1": {
          "y": 167,
          "x": 206
        },
        "contour_right3": {
          "y": 191,
          "x": 201
        }
    }
  ]
}

{
  "image_id": "W0pVzdW6XjPFu2fuazKODA==",
  "request_id": "1515662622,c9c626f1-11c7-4584-ba99-b731b7046c44",
  "time_used": 250,
  "faces": [
    {
      "landmark": {
        "contour_chin": {
          "y": 269,
          "x": 73
        },
        "left_eye_upper_left_quarter": {
          "y": 135,
          "x": 67
        },
        "mouth_lower_lip_right_contour1": {
          "y": 230,
          "x": 98
        },
        "left_eye_bottom": {
          "y": 143,
          "x": 72
        },
        "mouth_lower_lip_right_contour2": {
          "y": 238,
          "x": 104
        },
        "contour_left7": {
          "y": 176,
          "x": 49
        },
        "contour_left6": {
          "y": 166,
          "x": 49
        },
        "contour_left5": {
          "y": 157,
          "x": 51
        },
        "contour_left4": {
          "y": 148,
          "x": 54
        },
        "contour_left3": {
          "y": 139,
          "x": 58
        },
        "contour_left2": {
          "y": 131,
          "x": 61
        },
        "contour_left1": {
          "y": 124,
          "x": 64
        },
        "left_eye_lower_left_quarter": {
          "y": 139,
          "x": 66
        },
        "contour_right1": {
          "y": 167,
          "x": 206
        },
        "contour_right3": {
          "y": 191,
          "x": 201
        }
    }
  ]
}

If will always prompt error right after it successfully done the first json structure. Thanks

**Comment by vinay20045** [comment]
Hey, I would suggest you to write a pre-processor that'll convert your json structure to a list of json objects which can then be converted to csv using the script.
