### ISSUE TITLE
Python 3 CSV NewLine

### ISSUE THREAD

**Issue by frivollier** [vinay20045/json-to-csv#18]
In Python3 there is a know issue when writing line with csv lib.
https://stackoverflow.com/questions/3348460/csv-file-written-with-python-has-blank-lines-between-each-row

I added newline ='' to the file open function to solve this.

Line 92 open(csv_file_path, 'w+',newline ='')

Thanks for sharing this code

**Comment by vinay20045** [comment]
Yeah, and as that thread points out, this seems to be a **windows only** problem and you could also try opening the file in binary mode as opposed to text mode.

I see that this is your first issue... Great job!!
