### ISSUE TITLE
Array of complex objects?

### ISSUE THREAD

**Issue by VictorioBerra** [vinay20045/json-to-csv#21]
What would that look like?

IE:

```json
[
    {
        "name":"Apple",
        "binomial name":"Malus domestica",
        "major_producers":[
            {
                "name": "China",
                "amount": 100,
            }, 
            {
                "name": "United States",
                "amount": 200,
            }, 
            {
                "name": "Turkey",
                "amount": 300,
            }, 
        ]
    },
]
```

Would there just be a number added to the columns (`fruit_major_producers_1_name, fruit_major_producers_1_amount`)? What if fruit 2 (not pictured) had greater or less than fruit 1 number of major producers? Null columns?

**Comment by vinay20045** [comment]
1. The number, in this case, indicates the position within the array and not any sorting order.
2. If some value does not exist, it will contain blank in the csv at that position. The script needs at least 1 key to determine header.

If you're interested, I've explained all these and more in this post... https://askvinay.com/#post?Converting-Nested-JSON-to-CSV

**Comment by VictorioBerra** [comment]
I read that, in none of the examples do you show a nested array of complex objects as I show above. What would the columns look like?

![image](https://user-images.githubusercontent.com/2934507/40865728-73bd5a42-65bf-11e8-973c-73d7ee6c3b47.png)

**Comment by vinay20045** [comment]
I do not see what _"...nested array of complex objects..."_ you want to discuss. All I see is the array from my sample files in your above message.

Can you paste a sample set from your JSON please?

**Comment by VictorioBerra** [comment]
My Json sample is not verbatim yours, I modified major_producers to have additional properties. (An ID for example)

**Comment by VictorioBerra** [comment]
I'm wondering how that would be displayed

**Comment by vinay20045** [comment]
Can you post a sample?

**Comment by VictorioBerra** [comment]
Look at major_producers and notice how it is no longer a list of strings, but it is now a lost of objects each with a name and amount property.


```
[
    {
        "name":"Apple",
        "binomial name":"Malus domestica",
        "major_producers":[
            {
                "name": "China",
                "amount": 100,
            }, 
            {
                "name": "United States",
                "amount": 200,
            }, 
            {
                "name": "Turkey",
                "amount": 300,
            }, 
        ]
    },
]
```

**Comment by vinay20045** [comment]
If you can imagine each level 1 object to be a tree. Then, an array or an object, no matter at what nesting level it appears, will be reduced by following these 2 rules...

1. The value will always be the leaf node.
```Ex: China or 100```

2. The key will be the concatenation of all parent node names with an '_' as separator.
```Ex: fruit_major_producers_0_name or fruit_major_producers_0_amount```
2.1. In case of Arrays, the immediate parent of the value is the index
``` this is why the number 0 is appended, it is the index of that object within major_producers array```

These rules from the post I referenced above...

<img width="970" alt="screen shot 2018-06-01 at 7 22 50 pm" src="https://user-images.githubusercontent.com/2663192/40867321-4c94ffb2-65d1-11e8-8b87-1c9279fe991a.png">

Hope it helps!!

**Comment by VictorioBerra** [comment]
Helps a lot. Thanks for the quick replies.
