### ISSUE TITLE
NameError: global name 'reduced_item' is not defined

### ISSUE THREAD

**Issue by ron819** [vinay20045/json-to-csv#22]
This is the format of my JSON file:
![image](https://user-images.githubusercontent.com/40163787/41819624-1dd506e2-77cc-11e8-8ffa-a768e961094a.PNG)

I want to unpack the results to CSV file with the script.
Basically it should be 12 rows of data in CSV.

The script fails (Python 2.7):
```
    reduced_item[to_string(key)] = to_string(value)
NameError: global name 'reduced_item' is not defined
```

**Comment by vinay20045** [comment]
Have you changed something in the script? Try running it without changing anything first and then trace back your changes one by one to see where the issues might be.

Lines 82 and 41 will be a good place to start.

**Comment by vinay20045** [comment]
Yeah, that won't work. You have to do some more changes to be able to use it as a lib. There is already an open issue #6 and I'm yet to get around to working on it.

If you do make it work, please consider sending a PR and I will gladly review it.
