### ISSUE TITLE
Json to multipule CSV  - Feature request

### ISSUE THREAD

**Issue by ron819** [vinay20045/json-to-csv#23]
Hi,

I have the following JSON
![355](https://user-images.githubusercontent.com/40163787/41841829-f2953230-7871-11e8-8ac9-3e53d24b2605.PNG)

Nested Json with arrays that might also contain Jsons.

The current script creates single CSV file. however if arrays with Json are involved the CSV file is unreadable. As you can see in the image my Json has 3 rows : {0}, {1}, {2} each row contains the JSON to map key to columns and value to value. However when array are involved it gets ugly. {0} can have array of 5 items while {1} can have array of {2} items. this means many blank cells. now imagine one of the rows has 1000 items. It will create 1000 columns just for one row. The rest are blank.

The solution for such issue is whenever array is encountered unpack it to a new CSV file. In such approach there won't be columns mixed with row values such as:  `NODE_items_0_itemid` , `NODE_items_1_itemid` it will have only `NODE_items_itemid`. 

This is a major enhancement to the script and I'm aware that not all users want such behavior so you could offer two versions of the script. Let me know if you think it's a good idea.

**Comment by vinay20045** [comment]
Thank you for the suggestion. However, like you have already assessed, this is a very specific use case. I do not think I will be able to implement this anytime soon. I strongly suggest you to fork the script and make the changes you want.

Sorry, couldn't be more helpful here :( Do let me know how it goes...

**Comment by ron819** [comment]
@vinay20045 
Well it's not that specific.. Many needs it:
https://www.snellman.net/blog/archive/2016-01-12-json-to-multicsv/

This is needed by any one who uses relational databases. Basically it's to convert the Json to relations data base form (like: PostrgeSQL, MySQL, RedShift etc..)

It's just that there is no available Python version anywhere.
