### ISSUE TITLE
Unable to get the desired response

### ISSUE THREAD

**Issue by divyam8** [vinay20045/json-to-csv#24]
JSON File:
{
      
	"1c21528060728955": {
		"2018-06-04": 1,
		"2018-06-03": 0,
		"2018-06-02": 0,
		"2018-06-01": 0
	},
	"ffa1528090909651": {
		"2018-06-04": 1,
		"2018-06-03": 0,
		"2018-06-02": 0,
		"2018-06-01": 0
	}
}
Result by using json-to-csv 
""
"1c21528060728955"
"ffa1528090909651"

Expected result:
                                  2018-06-04  2018-06-03  2018-06-02  2018-06-01
1c21528060728955         1                  0                    0                 0
ffa1528090909651           1                  0                    0                 0

**Comment by Naman27** [comment]
Can you please tell me how to run this script?? . My json file is on desktop and i wanted to get output in a csv file on desktop .
Trying to convert   https://api.github.com/users/naman27/repos    
Execution instructions are written but i am unable to fig. it out.

**Comment by divyam8** [comment]
python json_to_csv.py  "fruit"  ~/Desktop/json-to-csv/samples/sample.json  ~/Desktop/json-to-csv/samples/sample.csv

**Comment by Naman27** [comment]
Thank you for your help !!!
But not getting the output  in desired format 

Want output like this....
![c](https://user-images.githubusercontent.com/25168409/42218969-e8169c3c-7ee7-11e8-95a4-e3cf53f922d3.JPG)

but getting in this format 
![c2](https://user-images.githubusercontent.com/25168409/42219135-6c474c54-7ee8-11e8-9b20-5443a9469dd4.JPG)

**Comment by vinay20045** [comment]
@divyam8 You will not get the desired output for your JSON format. You need to have a list/array of items. Please check the readme file for supported formats.

@Naman27 I saved the JSON from the github api and ran the script like shown below and got the results correctly with 6 rows. Are you running the script correctly? Check the instructions in the readme file if you are still facing any issue.

<img width="872" alt="screen shot 2018-07-03 at 9 28 05 am" src="https://user-images.githubusercontent.com/2663192/42222633-b9cc5bda-7ea3-11e8-9ac4-5bff7d91bbd8.png">
<img width="838" alt="screen shot 2018-07-03 at 9 23 21 am" src="https://user-images.githubusercontent.com/2663192/42222648-c1e48acc-7ea3-11e8-8719-8d135d2ca449.png">

**Comment by Naman27** [comment]
@vinay20045  
![c3](https://user-images.githubusercontent.com/25168409/42225385-16dada6c-7efa-11e8-8054-1e3b4f5ea2a7.JPG)
I tried the same  but not getting the desired output .
I am using windows is this creating a problem?????

**Comment by vinay20045** [comment]
I don't thing Windows is the problem here. Are you saving the JSON output of the github api without any modification? Just try saving the api output as is.

**Comment by Naman27** [comment]
Yes i am saving the data without any modification . 
Python code is calling the api and saving the data in a json file.

To test my json data i tried converting using https://json-csv.com/ and got the desired output  so i think my json data is not corrupt .

**Comment by vinay20045** [comment]
Glad to hear that some other script worked out for you. 

I'm out of ideas now as to why it is giving you 6300 cols. If you are hell bent on getting this script to work, please send me an email (vinay@askvinay.com) with the exact files you are using... (json, csv and the python script file) along with the details of your platform and any other details you can add. I will try to debug it.

**Comment by Naman27** [comment]
@vinay20045  Pardon for late reply.
I am unable to debug my issue so i have forwarded you a  mail regarding that . Please try to debug.

**Comment by Naman27** [comment]
@vinay20045  
Thanks a ton for debugging my issue!
