### ISSUE TITLE
Node_name: What is it?

### ISSUE THREAD

**Issue by seanmavley** [vinay20045/json-to-csv#3]
`python /path/to/json_to_csv.py node_name json_in_file_path csv_out_file_path`

what is the `node_name`?

**Comment by vinay20045** [comment]
This is the name of the element which holds the array. Please refer to the [readme](https://github.com/vinay20045/json-to-csv/blob/master/README.md) file and [sample json file](https://github.com/vinay20045/json-to-csv/blob/master/sample.json) to understand more...
