### ISSUE TITLE
I can't convert a file

### ISSUE THREAD

**Issue by efratushava** [vinay20045/json-to-csv#31]
Hello, 

Thank you, it's an excellent script.

I have a problem:
I'm trying to convert a valid json file, and I get this error:
_csv.Error: need to escape, but no escapechar set

What can I do?

**Comment by vinay20045** [comment]
I can't debug this issue without being able to reproduce it. Can you reopen the issue by providing sample from the file you are using, specifically around the line where you are getting this error?
