### ISSUE TITLE
converting json to csv with keys and dictionary

### ISSUE THREAD

**Issue by hrc387** [vinay20045/json-to-csv#35]
i am downloading an API from a website, download it as export.json.  now i am trying to convert that to .csv but with only certain keys or dictionarys.  i think its nested but not sure.  see attached .json file.  i want to convert only the fieldId8, fieldId9, and fieldId2 into the csv file.
[Export.zip](https://github.com/vinay20045/json-to-csv/files/5277617/Export.zip)

**Comment by vinay20045** [comment]
Hi @hrc387,

You currently cannot filter out the fields from processing like how you are expecting. 

However, I took a look at the file you have sent and I think you can get what you want by running the script with **result** as your node name. Like... `python json_to_csv.py result Export.json Export.csv` This gives a csv with 8 cols from which you can delete the cols you don't want. Output file Attached.
[Export.csv.zip](https://github.com/vinay20045/json-to-csv/files/5319413/Export.csv.zip)

I see a pull request #36 which seems to be trying to add this feature. I believe it warrants a discussion. You can follow that thread if interested.
