### ISSUE TITLE
No "node" name

### ISSUE THREAD

**Issue by Aubreymcfato** [vinay20045/json-to-csv#4]
Hi Vinay, I wanted to try your script but unfortunately my (large) JSON does not have the name for the node I want to trasform in a csv row. Basically, my JSON is a list of dictionaries, and I want the script to take all the dictionaries.

**Comment by vinay20045** [comment]
Hi Aubrey, I've added support for list of dictionaries. Please do the following...
1. pull code and new branches.
2. switch to branch `handling_list_of_dictionaries`.
3. run the script against your file.
4. keep node name as any useful name for you. I kept `fruit` in case of `samples/sample_2.json` file.

I've tested it on `samples/sample_2.json`. Please let me know if it works well for you. I will then merge code to master.
