### ISSUE TITLE
Invalid syntax when executing script

### ISSUE THREAD

**Issue by steveermish** [vinay20045/json-to-csv#9]
When executing the script with or without arguments, using Python 2.7 or 3.6.3 on a Mac:
File "jsoncsv.py", line 51
    elif type(value) is dict:
       ^
SyntaxError: invalid syntax

**Comment by vinay20045** [comment]
No errors at my end, similar environment as yours.

Have you modified the code? Can you post a code snippet and the command you are running?

**Comment by steveermish** [comment]
I haven't modified anything, just copy past to json_to_csv.py.  Below are command examples.  I am running this on Mac in Bash, not sure if that's an issue.

$ python json_to_csv.py
  File "json_to_csv.py", line 51
    elif type(value) is dict:
       ^
SyntaxError: invalid syntax

$ python json_to_csv.py records response.json response.csv
  File "json_to_csv.py", line 51
    elif type(value) is dict:
       ^
SyntaxError: invalid syntax

**Comment by steveermish** [comment]
FYI, as a test, I cloned your repository and the file runs fine.  I've compared the files between copy/paste of the code and the cloned file and they are identical.  Very odd, but at least I have a workaround.
